### ISSUE TITLE
yaffs_decrypt exception when decrypting T57 firmware

### ISSUE THREAD

**Issue by electroniceel** [synacktiv/yealink_tools#1]
I successfully decrypted the update roms for a T46S. Thank you for making that easy!

I wanted to compare the firmware structure with newer models so I tried it with "T57W-97.84.0.85.rom". The yealink_rom_dump step works flawlessly. But when running yaffs_decrypt on the included rfs.bin I get:

```
$ python3 yaffs_decrypt.py dump rfs.bin 
Generating blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21783/21783 [00:04<00:00, 4497.25it/s]
Reconstructing objects:   0%|                                                                                                                                              | 0/21783 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "yaffs_decrypt.py", line 360, in <module>
    main()
  File "yaffs_decrypt.py", line 356, in main
    args.func(args)
  File "yaffs_decrypt.py", line 309, in dump_fs
    filesystem = reconstruct_filesystem(args.file)
  File "yaffs_decrypt.py", line 272, in reconstruct_filesystem
    filesystem.add_blocks(blocks)
  File "yaffs_decrypt.py", line 256, in add_blocks
    self.add_block(block)
  File "yaffs_decrypt.py", line 243, in add_block
    tag = Yaffstag.from_bytes(block.spare)
  File "/usr/lib/python3.7/site-packages/kaitaistruct.py", line 43, in from_bytes
    return cls(KaitaiStream(BytesIO(buf)))
  File "~/tmp/yealink_tools/yaffstag.py", line 18, in __init__
    self._read()
  File "~/tmp/yealink_tools/yaffstag.py", line 32, in _read
    self.crypto_magic = self._io.ensure_fixed_contents(b"\x15\x08\x86\x19")
  File "/usr/lib/python3.7/site-packages/kaitaistruct.py", line 279, in ensure_fixed_contents
    (actual, expected)
Exception: unexpected fixed contents: got b'\x00\x00\x00\x00', was waiting for b'\x15\x08\x86\x19'

```
If it makes any difference, this is with python3-3.7.4 and kaitai-0.8 on Fedora 30.

**Comment by synacktiv-tp** [comment]
Hi! Thanks for using this tool !
It seems that the T57 is no longer based on a YAFFS file system, so the `yaffs_decrypt.py` will not work to extract this filesystem.

From what I see, it's almost a normal UBIFS filesystem, but similarly as the Yaffs one, some headers are ciphered.

Good luck in extracting it!

Best regards

**Comment by johnkeates** [comment]
I'm running in to the same thing with W60B and T57W firmwares, both use UBIFS as well (and encrypted too). Did you ever find a way to decrypt those filesystems @electroniceel ?

**Comment by electroniceel** [comment]
sorry, I did not look any deeper into decoding the T57 fw.
