### ISSUE TITLE
Decryption for T58V-Firmware does not work

### ISSUE THREAD

**Issue by Flole998** [synacktiv/yealink_tools#4]
I'm trying to decrypt the T58V-Firmware but I am getting the following errors:

```
# python3 yealink_rom_dump.py --verbose info ../T58V\(T56A\)-58.86.0.26.rom
ROM magic: 0xb'ad24ec0b'
header size 0x80
header CRC32: 0x132af291
header format 0x3
Image cryptography: AES
header flags 0x2
content size 0xf3db190
ROM verify: 0xffffffff
ROM blocks: 0x6
ROM dev ID: 55
ROM hw ID: 1
ROM sw ID: 0
ROM dev name: T58V
ROM oem name: NULL
ROM  version: 58.86.0.26
Rom rom cid 0 : 72
INFO:root:Decrypting the ROM file
Decrypting blocks:   0%|                                                                                                                              | 0/6 [00:00<?, ?it/s]DEBUG:root:Header size 0xbdb5cb90
DEBUG:root:block  size 0xfdb8cf05
ERROR:root:Error, invalid data
Decrypting blocks:  17%|███████████████████▋                                                                                                  | 1/6 [00:00<00:00,  7.50it/s]DEBUG:root:Header size 0xaec72ef
DEBUG:root:block  size 0x7f6916cd
ERROR:root:Error, invalid data
Decrypting blocks:  33%|███████████████████████████████████████▎                                                                              | 2/6 [00:00<00:00,  7.39it/s]DEBUG:root:Header size 0x6f932af7
DEBUG:root:block  size 0x51cb3115
ERROR:root:Error, invalid data
Decrypting blocks:  50%|███████████████████████████████████████████████████████████                                                           | 3/6 [00:01<00:01,  1.65it/s]DEBUG:root:Header size 0x58817793
DEBUG:root:block  size 0x6f6b03f2
ERROR:root:Error, invalid data
DEBUG:root:Header size 0x6f03d8b5
DEBUG:root:block  size 0x289fb9eb
ERROR:root:Error, invalid data
Decrypting blocks:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 5/6 [00:03<00:00,  1.14it/s]DEBUG:root:Header size 0xd0f1b6a3
DEBUG:root:block  size 0x5a5a4bbe
ERROR:root:Error, invalid data
Decrypting blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:05<00:00,  1.12s/it]
Traceback (most recent call last):
  File "yealink_rom_dump.py", line 233, in <module>
    main()
  File "yealink_rom_dump.py", line 229, in main
    actions[args.action](args.update)
  File "yealink_rom_dump.py", line 180, in show_info
    show_rom_info(mupdate, fname)
  File "yealink_rom_dump.py", line 171, in show_rom_info
    update = yealinkrom.Yealinkrom.from_bytes(data)
  File "/home/flole/.local/lib/python3.6/site-packages/kaitaistruct.py", line 52, in from_bytes
    return cls(KaitaiStream(BytesIO(buf)))
  File "/tmp/yealink_tools/yealinkrom.py", line 34, in __init__
    self._read()
  File "/tmp/yealink_tools/yealinkrom.py", line 46, in _read
    self.blocks.append(Yealinkrom.Block(self._io, self, self._root))
  File "/tmp/yealink_tools/yealinkrom.py", line 132, in __init__
    self._read()
  File "/tmp/yealink_tools/yealinkrom.py", line 137, in _read
    self.hdr = Yealinkrom.BlockHeader(_io__raw_hdr, self, self._root)
  File "/tmp/yealink_tools/yealinkrom.py", line 55, in __init__
    self._read()
  File "/tmp/yealink_tools/yealinkrom.py", line 60, in _read
    raise kaitaistruct.ValidationNotEqualError(b"\xEB\x9F\x56\xC9", self.magic, self._io, u"/types/block_header/seq/0")
kaitaistruct.ValidationNotEqualError: /types/block_header/seq/0: at pos 4: validation failed: not equal, expected b'\xeb\x9fV\xc9', but got b'\x07\xcd0|' 
```

Do you have any idea what needs to be changed so the T58V-Firmware can be decrypted aswell?

**Comment by fuomag9** [comment]
#1 can probably give you a hint, they changed the file system and probably the encryption type as well

**Comment by Flole998** [comment]
Any idea how I could manage to extract some binaries from the phone? If I can get a copy of the updater binary then I can load it in IDA....

**Comment by fuomag9** [comment]
> Any idea how I could manage to extract some binaries from the phone? If I can get a copy of the updater binary then I can load it in IDA....

I managed to extract some stuff by manually unpacking (I have a w60b) but I could not extract everything since they changed how their encryption works and I lack the knowledge to reverse that.

I'm personally trying to develop a CFW or achieve root on the device (which would make dumping the firmware easier as we'd have access to the decryption stage during an update and it'd make reversing easier)

**Comment by Flole998** [comment]
It might be a lot easier than initially thought: As far as I understand it's part of U-Boot/the linux kernel. Both are licensed under the GPL, so you should be able to just ask for a copy of the source code and then just look in the source code for the decryption algorithm. Ask for the specific Firmware Version you're using, then it should contain the right parts and they can't simply change it so interesting stuff is no longer there ;)

**Comment by fuomag9** [comment]
> It might be a lot easier than initially thought: As far as I understand it's part of U-Boot/the linux kernel. Both are licensed under the GPL, so you should be able to just ask for a copy of the source code and then just look in the source code for the decryption algorithm. Ask for the specific Firmware Version you're using, then it should contain the right parts and they can't simply change it so interesting stuff is no longer there ;)

I'll try asking for a copy of the source code, but as it's a company based in China you can guess what happens with honouring GPL licenses there :(

I've made some reverse functions to try to develop a cfw but the rom is marked as invalid when uploaded, so they probably added some checks (signature or CRC maybe) after the initial post referenced by this repository.

**Comment by trideeindhoven** [comment]
I find that most firmwares are no longer decryptable. I would love to make a new version of this script, but i don't have enough skill to do this. Should we team up and try to make a new version that works on the latest version of the f/w?

**Comment by fuomag9** [comment]
> I find that most firmwares are no longer decryptable. I would love to make a new version of this script, but i don't have enough skill to do this. Should we team up and try to make a new version that works on the latest version of the f/w?

I have reverse skills but I lack cryptography knowledge (for example in my case I have the kernel in decrypted form, and a  app.bin which probably contains code for decryption of the image)

**Comment by trideeindhoven** [comment]
How did you extract the bin files? I get an error when performing the yealink_rom_dump.py Did you change somethingin the source?

**Comment by fuomag9** [comment]
> How did you extract the bin files? I get an error when performing the yealink_rom_dump.py Did you change somethingin the source?

What is your error? If it's due to missing libraries you have to generate the kaitai .py files (which are missing in the repository)

This is my fork (I also have them generated in the repository https://git.fuo.fi/fuomag9/yealink_tools )
